spring:
  application:
    name: server-registry
  cloud:
    config:
      import-check:
        enable : false

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
